In [1]:
import numpy as np

In [4]:
arr1 = np.array ([1,2,3,4,5])
mask = arr1 % 2 == 0
mask

array([False,  True, False,  True, False])

In [22]:
# Definindo a matriz 3D
pessoas_id_idade = np.array([[[1, 22], [2, 21], [3, 27], [4, 26]]])

In [23]:
# Verificar a forma da matriz original
print("Shape da matriz original:", pessoas_id_idade.shape)  # Deve mostrar (1, 4, 2)

Shape da matriz original: (1, 4, 2)


In [24]:
# Transformar a matriz 3D para 2D
pessoas_id_idade_2d = pessoas_id_idade.reshape(-1, 2)

In [25]:
# Verificar a forma da matriz 2D
print("Shape da matriz 2D:", pessoas_id_idade_2d.shape)  # Deve mostrar (4, 2)

Shape da matriz 2D: (4, 2)


In [26]:
# Verificar o conteúdo da matriz 2D
print("Conteúdo da matriz 2D:\n", pessoas_id_idade_2d)

Conteúdo da matriz 2D:
 [[ 1 22]
 [ 2 21]
 [ 3 27]
 [ 4 26]]


In [27]:
# Criar uma máscara booleana para idades maiores de 21
mask_maior21 = pessoas_id_idade_2d[:, 1] > 21

In [28]:
# Verificar a máscara booleana
print("Máscara booleana:", mask_maior21)  # Deve mostrar [ True False  True True]

Máscara booleana: [ True False  True  True]


In [29]:
# Filtrar as pessoas maiores de 21
pessoas_maiores_21 = pessoas_id_idade_2d[mask_maior21]

In [30]:
# Verificar o resultado do filtro
print("Pessoas maiores de 21:\n", pessoas_maiores_21)

Pessoas maiores de 21:
 [[ 1 22]
 [ 3 27]
 [ 4 26]]


In [32]:
# Usar np.where para encontrar os índices onde a idade é maior que 21
indices_maior21 = np.where(pessoas_id_idade_2d[:, 1] > 21)

# Verificar os índices
print("Índices onde a idade é maior que 21:", indices_maior21)

Índices onde a idade é maior que 21: (array([0, 2, 3], dtype=int64),)


In [33]:
cartela_bingo = np.array ([[16, 10, 3, 15],
                         [14, 23, 17, 27],
                         [6, 19, 3, 1],
                         [10, 4, 18, 19]])
cartela_bingo

array([[16, 10,  3, 15],
       [14, 23, 17, 27],
       [ 6, 19,  3,  1],
       [10,  4, 18, 19]])

In [35]:
np.where(cartela_bingo % 3 == 0, "div3", cartela_bingo) # quero pegar todos os numeros que sáo divisiveis por 3

array([['16', '10', 'div3', 'div3'],
       ['14', '23', '17', 'div3'],
       ['div3', '19', 'div3', '1'],
       ['10', '4', 'div3', '19']], dtype='<U11')

In [38]:
p = np.where(pessoas_id_idade_2d > 21, "maior idade", pessoas_id_idade_2d)
p #apontar todos que sáo maiores de idade a partir da frase acima

array([['1', 'maior idade'],
       ['2', '21'],
       ['3', 'maior idade'],
       ['4', 'maior idade']], dtype='<U11')

In [39]:
type (p[0,0]) #transformando os que sao maiores de idade de int para string

numpy.str_