In [3]:
import numpy as np

In [4]:
l = [1, 2, 3, 4]
arrl = np.array(l)

In [5]:
arrl

array([1, 2, 3, 4])

In [6]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [7]:
list(range(0,3))

[0, 1, 2]

In [8]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr_range = np.arange(1,11)
arr_range

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
type(arr_range)

numpy.ndarray

In [11]:
np.random.random((3,3))

array([[0.35485215, 0.10138725, 0.60376147],
       [0.72959736, 0.55245894, 0.28744034],
       [0.73987974, 0.82486994, 0.53155069]])

1. CRIE UM ARRAY COM 4 LINHAS E 3 COLUNAS COM VALORES ALEATÓRIOS

In [12]:
np.random.random((4,3))

array([[0.12127467, 0.87377303, 0.87059052],
       [0.2531848 , 0.76861815, 0.26256172],
       [0.49070803, 0.82720449, 0.69080179],
       [0.09928379, 0.45450507, 0.16673069]])

2. CRIE UM ARRAY COM 5 COLUNAS E 10 LINHAS INICIALIZADAS COM ZERO

In [13]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

3. CRIE UM ARRAY COM VALORES INTEIROS, 3 LINHAS E 5 COLUNAS COM VALORES ALEATÓRIOS

In [14]:
np.random.randint(10,30, size=(3,5))

array([[15, 16, 18, 23, 13],
       [24, 23, 28, 28, 18],
       [19, 11, 29, 29, 16]])

ARRAY COM 3 DIMENSÕES

In [18]:
arr1_2d = np.array([[1,2],[3,4]])
arr2_2d = np.array([[5,6],[7,8]])
arr3_2d = np.array([[9,2],[3,4]])

arr_3d = np.array([arr1_2d, arr2_2d, arr3_2d])

In [16]:
arr3_2d

array([[9, 2],
       [3, 4]])

In [19]:
arr_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[9, 2],
        [3, 4]]])

In [24]:
arr = np.zeros((3,4,2))

In [26]:
arr.shape

(3, 4, 2)

In [27]:
arr.flatten()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0.])

REDUZA O ARRAY (5,7) A APENAS UMA DIMENSÃO

In [29]:
a57 = np.random.random((5,7))
a57 = a57.flatten()
a57

array([0.0152768 , 0.95219532, 0.40076389, 0.58465197, 0.00130569,
       0.91088174, 0.46652759, 0.48780761, 0.09437041, 0.36139864,
       0.19072107, 0.54499754, 0.34400788, 0.51888417, 0.17969809,
       0.7665751 , 0.04223449, 0.96841977, 0.60189561, 0.91265508,
       0.99973402, 0.04451794, 0.45102299, 0.76461124, 0.31299277,
       0.30460964, 0.08804834, 0.96254932, 0.93277095, 0.34498965,
       0.01852904, 0.96027427, 0.31686054, 0.52141363, 0.96388434])

CONSIDERANDO QUE VOCÊ É UMA ORGANIZADORA DE UM JOGO DE BINGO. CRIE UM ARRAY QUE IRÁ REPRESENTAR A CARTILHA DESSES JOGOS DE BINGO. OS NÚMEROS DE SUAS CARTELAS VARIAM ENTRE 1 E 30, E VOCÊ TERÁ 10 PARTICIPANTES. CADA CARTELA TERÁ 12 NÚMEROS (4,3). CRIE UM ARRAY QUE REPRESENTE ESSE JOGO,

In [32]:
bingo = np.random.randint(1,31, size=(10,4,3)) #usar o np.random para gerar números aleatórios e o randint para definir a quantidade de coluna e tamanho
bingo

array([[[10, 14, 27],
        [30, 18,  9],
        [10, 15,  1],
        [ 7,  6, 10]],

       [[12,  8, 30],
        [ 5, 25, 11],
        [16,  7, 25],
        [21, 21, 18]],

       [[12,  2, 10],
        [23, 15, 16],
        [16, 27, 11],
        [10, 18, 25]],

       [[ 3, 26, 16],
        [ 7, 12, 21],
        [17,  3,  6],
        [24, 29, 23]],

       [[ 7, 10, 22],
        [ 8, 11,  7],
        [ 8, 30, 16],
        [20, 16, 20]],

       [[17, 13, 29],
        [ 9,  1, 14],
        [18,  1, 13],
        [ 2, 17,  8]],

       [[27,  1, 11],
        [25, 15, 14],
        [10, 18, 29],
        [21, 15, 28]],

       [[14,  2,  1],
        [ 7,  3, 21],
        [20, 12, 24],
        [ 3, 25,  3]],

       [[30,  1, 28],
        [15,  8, 29],
        [ 1, 23, 29],
        [22, 13, 11]],

       [[23,  8, 20],
        [17, 14, 29],
        [ 1, 17, 26],
        [18, 15, 24]]])

FAÇA UM RESHAPE DAS SUAS CARTELAS PARA QUE HAJA 5 CARTELAS DE 4 LINHAS E 6 COLUNAS

In [33]:
bingo.reshape(5,4,6)

array([[[10, 14, 27, 30, 18,  9],
        [10, 15,  1,  7,  6, 10],
        [12,  8, 30,  5, 25, 11],
        [16,  7, 25, 21, 21, 18]],

       [[12,  2, 10, 23, 15, 16],
        [16, 27, 11, 10, 18, 25],
        [ 3, 26, 16,  7, 12, 21],
        [17,  3,  6, 24, 29, 23]],

       [[ 7, 10, 22,  8, 11,  7],
        [ 8, 30, 16, 20, 16, 20],
        [17, 13, 29,  9,  1, 14],
        [18,  1, 13,  2, 17,  8]],

       [[27,  1, 11, 25, 15, 14],
        [10, 18, 29, 21, 15, 28],
        [14,  2,  1,  7,  3, 21],
        [20, 12, 24,  3, 25,  3]],

       [[30,  1, 28, 15,  8, 29],
        [ 1, 23, 29, 22, 13, 11],
        [23,  8, 20, 17, 14, 29],
        [ 1, 17, 26, 18, 15, 24]]])

TIPOS DE DADOS EM UM NUMPY ARRAY

In [34]:
np.array([5.4,6.7,2.1]).dtype

dtype('float64')

In [35]:
np.array([5,6,7]).dtype

dtype('int32')

In [36]:
np.array(["Hello", "Oi", "WoMakersCode"]).dtype

dtype('<U12')

In [58]:
x = [3,4,2.1]

In [59]:
x = np.array(x)

In [60]:
x = x.astype(np.int32)

In [61]:
np.array([True, 3, False]).dtype

dtype('int32')

In [62]:
np.array([True, 3, False])

array([1, 3, 0])

In [63]:
vf = np.array([True, 3, False])
vf

array([1, 3, 0])

In [66]:
vf.astype(np.bool8)

array([ True,  True, False])

In [67]:
vf.astype(np.int32)

array([1, 3, 0])