In [2]:
import numpy as np

In [3]:
arr = np.array([2,4,6,7,8])
arr [1]

4

In [4]:
arr [2]

6

In [5]:
cartela_bingo = np.array ([[16, 10, 3, 15],
                         [14, 23, 17, 27],
                         [6, 19, 3, 1],
                         [10, 4, 18, 19]])
cartela_bingo

array([[16, 10,  3, 15],
       [14, 23, 17, 27],
       [ 6, 19,  3,  1],
       [10,  4, 18, 19]])

In [6]:
#pegar uma coluna inteira
cartela_bingo[:, 1].reshape((4,1))

array([[10],
       [23],
       [19],
       [ 4]])

In [7]:
cartela_bingo[0]

array([16, 10,  3, 15])

In [8]:
np.sort(cartela_bingo)

array([[ 3, 10, 15, 16],
       [14, 17, 23, 27],
       [ 1,  3,  6, 19],
       [ 4, 10, 18, 19]])

In [9]:
np.sort(cartela_bingo, axis=0) #sortido

array([[ 6,  4,  3,  1],
       [10, 10,  3, 15],
       [14, 19, 17, 19],
       [16, 23, 18, 27]])

ID DE ESPECIE, QUANTIDADE DE REPRESENTANTES ENCONTRADOS, PROFUNDEZA, TAMANHO MÉDIO DA ESPÉCIE

In [10]:
especies = np.array ([[747, 89, 33, 5],
                     [623, 123, 32, 13],
                     [501, 22, 49, 2],
                     [116, 101, 42, 10],
                     [297, 56, 69, 22], 
                     [613, 64, 27, 7],
                     [295, 84, 29, 14],
                     [692, 105, 71, 16],
                     [229, 103, 35, 5],
                     [372, 124, 70, 1]])
especies

array([[747,  89,  33,   5],
       [623, 123,  32,  13],
       [501,  22,  49,   2],
       [116, 101,  42,  10],
       [297,  56,  69,  22],
       [613,  64,  27,   7],
       [295,  84,  29,  14],
       [692, 105,  71,  16],
       [229, 103,  35,   5],
       [372, 124,  70,   1]])

In [11]:
qtd_especies = especies [:, 1]
qtd_especies # selecione a segunda coluna com a qnt de especies encontradas e adicione um array como qtd_especies

array([ 89, 123,  22, 101,  56,  64,  84, 105, 103, 124])

In [12]:
print(qtd_especies[0:3]) #de qtd_especies selecione apenas as 3 primeiras quantidades e print

[ 89 123  22]


In [13]:
especies.shape

(10, 4)

In [14]:
qtd_especies[-5:] #printar os 5 ultimos da quantidade de especies, colocar negativo para pegar os ultimos

array([ 64,  84, 105, 103, 124])

In [15]:
#uma array que tenha o tamanho das especies em ordem crescente [:,3] e se for em ordem descrecente (especies[:,3])[::-1]
np.sort(especies[:,3])

array([ 1,  2,  5,  5,  7, 10, 13, 14, 16, 22])

In [16]:
especies

array([[747,  89,  33,   5],
       [623, 123,  32,  13],
       [501,  22,  49,   2],
       [116, 101,  42,  10],
       [297,  56,  69,  22],
       [613,  64,  27,   7],
       [295,  84,  29,  14],
       [692, 105,  71,  16],
       [229, 103,  35,   5],
       [372, 124,  70,   1]])

In [17]:
#usando um index booleano crie um array que contem os dados da maior especie encontrada, esse valor corresponde ao 22
#est[a na quarta coluna o numero 22
especies [:, 3] == 22

array([False, False, False, False,  True, False, False, False, False,
       False])

In [39]:
# como se fosse um slice da matriz
maior_especie = especies[especies [:, 3] == 22]
maior_especie

array([[297,  56,  69,  22]])

In [47]:
mask_297 = especies[:, 0] == 297

In [49]:
result = especies[mask_297]
result

array([[297,  56,  69,  22]])

In [50]:
#usando np.where() faça um array com a linha com dados correspodentes a especie com 105 representantes encontrados.
np.where(especies[:, 1] == 105)

(array([7], dtype=int64),)

In [51]:
especies[np.where(especies[:, 1] == 105)]

array([[692, 105,  71,  16]])

In [52]:
#considere a profundeza em que a especie foi encontrada e substitua esses valores maiores que 60 com "profundo"
np.where(especies[:, 2] > 60, "Profundo", especies [:, 2])

array(['33', '32', '49', '42', 'Profundo', '27', '29', 'Profundo', '35',
       'Profundo'], dtype='<U11')

OUTRA ATIVIDADE SOBRE AGREGADOS DE DADOS

In [53]:
cartela_bingo

array([[16, 10,  3, 15],
       [14, 23, 17, 27],
       [ 6, 19,  3,  1],
       [10,  4, 18, 19]])

In [60]:
cartela_bingo1 = cartela_bingo[:3]
cartela_bingo1

array([[16, 10,  3, 15],
       [14, 23, 17, 27],
       [ 6, 19,  3,  1]])

In [61]:
cartela_bingo2 = cartela_bingo[-1:]
cartela_bingo2

array([[10,  4, 18, 19]])

In [62]:
np.concatenate((cartela_bingo1, cartela_bingo2))

array([[16, 10,  3, 15],
       [14, 23, 17, 27],
       [ 6, 19,  3,  1],
       [10,  4, 18, 19]])

In [66]:
#TIRAR PROVA
cartela_bingo == np.concatenate((cartela_bingo1, cartela_bingo2))

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

ATIVIDADE SALA DE ESPERA

In [67]:
sala_espera = np.array([['5','30', '1', 'Alice'],
                      ['6','29', '1', 'Bob'],
                      ['7','35', '3', 'Cristina'],
                       ['8','34', '3', 'Luiz']])

In [68]:
#vamos deletar alguem
np.delete(sala_espera, 3, axis=0)

array([['5', '30', '1', 'Alice'],
       ['6', '29', '1', 'Bob'],
       ['7', '35', '3', 'Cristina']], dtype='<U8')

ATIVIDADE COM ESPECIES AINDA

In [69]:
especies

array([[747,  89,  33,   5],
       [623, 123,  32,  13],
       [501,  22,  49,   2],
       [116, 101,  42,  10],
       [297,  56,  69,  22],
       [613,  64,  27,   7],
       [295,  84,  29,  14],
       [692, 105,  71,  16],
       [229, 103,  35,   5],
       [372, 124,  70,   1]])

In [70]:
# adicione mais 2 especies ao array: [[204, 10, 40, 12], [392, 11, 81, 11]]
novas_especies = np.array([[204, 10, 40, 12], [392, 11, 81, 11]])

In [71]:
np.concatenate((especies, novas_especies))

array([[747,  89,  33,   5],
       [623, 123,  32,  13],
       [501,  22,  49,   2],
       [116, 101,  42,  10],
       [297,  56,  69,  22],
       [613,  64,  27,   7],
       [295,  84,  29,  14],
       [692, 105,  71,  16],
       [229, 103,  35,   5],
       [372, 124,  70,   1],
       [204,  10,  40,  12],
       [392,  11,  81,  11]])

In [75]:
#verificar informacoes sobre np.array([0,1,0,0,0,0,1,0,1,1,0])
especies.shape

(10, 4)

In [78]:
np.array([0,1,0,0,0,0,1,0,1,1]).shape

(10,)

In [80]:
#agora vou fazer um reshape
ver = np.array([0,1,0,0,0,0,1,0,1,1]).reshape((10,1))
ver

array([[0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1]])

In [82]:
#adicione +1 coluna no array original com o numero de especies encontradas com que indica se o animal enxerga ou não: [0,1,0,0,0,0,1,0,1,1,0]

np.concatenate((especies, ver), axis=1)

array([[747,  89,  33,   5,   0],
       [623, 123,  32,  13,   1],
       [501,  22,  49,   2,   0],
       [116, 101,  42,  10,   0],
       [297,  56,  69,  22,   0],
       [613,  64,  27,   7,   0],
       [295,  84,  29,  14,   1],
       [692, 105,  71,  16,   0],
       [229, 103,  35,   5,   1],
       [372, 124,  70,   1,   1]])

SALVAR ARRAY

In [84]:
arr2d = np.array([[1,2,3], [4,5,6]])
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
arr3d = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])
arr3d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [88]:
arr3d.shape

(2, 2, 3)

In [91]:
#salvar em formato de arquivo de csv
np.savetxt('arr2d.csv', arr2d, delimiter=',')

In [93]:
#salvar em formato de arquivo de txt
np.savetxt('arr2d', arr2d, delimiter=',')

In [98]:
#salvar em npy
np.save('arr3d.npy', arr3d)

In [99]:
#para carregar o arquivo
arr_saved_3d = np.load('arr3d.npy')
arr_saved_3d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [101]:
arr_saved_3d.shape

(2, 2, 3)